//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Database1Model", "FK_Carreras_TipoCarrera", "TipoCarrera", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(udb3.Models.TipoCarrera), "Carreras", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(udb3.Models.Carreras), true)]
[assembly: EdmRelationshipAttribute("Database1Model", "FK_Contactos_TipoContacto", "TipoContacto", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(udb3.Models.TipoContacto), "Contactos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(udb3.Models.Contactos), true)]

#endregion

namespace udb3.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Database1Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Database1Entities object using the connection string found in the 'Database1Entities' section of the application configuration file.
        /// </summary>
        public Database1Entities() : base("name=Database1Entities", "Database1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Database1Entities object.
        /// </summary>
        public Database1Entities(string connectionString) : base(connectionString, "Database1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Database1Entities object.
        /// </summary>
        public Database1Entities(EntityConnection connection) : base(connection, "Database1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Carreras> Carreras
        {
            get
            {
                if ((_Carreras == null))
                {
                    _Carreras = base.CreateObjectSet<Carreras>("Carreras");
                }
                return _Carreras;
            }
        }
        private ObjectSet<Carreras> _Carreras;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TipoCarrera> TipoCarrera
        {
            get
            {
                if ((_TipoCarrera == null))
                {
                    _TipoCarrera = base.CreateObjectSet<TipoCarrera>("TipoCarrera");
                }
                return _TipoCarrera;
            }
        }
        private ObjectSet<TipoCarrera> _TipoCarrera;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Contactos> Contactos
        {
            get
            {
                if ((_Contactos == null))
                {
                    _Contactos = base.CreateObjectSet<Contactos>("Contactos");
                }
                return _Contactos;
            }
        }
        private ObjectSet<Contactos> _Contactos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TipoContacto> TipoContacto
        {
            get
            {
                if ((_TipoContacto == null))
                {
                    _TipoContacto = base.CreateObjectSet<TipoContacto>("TipoContacto");
                }
                return _TipoContacto;
            }
        }
        private ObjectSet<TipoContacto> _TipoContacto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Noticias> Noticias
        {
            get
            {
                if ((_Noticias == null))
                {
                    _Noticias = base.CreateObjectSet<Noticias>("Noticias");
                }
                return _Noticias;
            }
        }
        private ObjectSet<Noticias> _Noticias;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Carreras EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCarreras(Carreras carreras)
        {
            base.AddObject("Carreras", carreras);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TipoCarrera EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTipoCarrera(TipoCarrera tipoCarrera)
        {
            base.AddObject("TipoCarrera", tipoCarrera);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Contactos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContactos(Contactos contactos)
        {
            base.AddObject("Contactos", contactos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TipoContacto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTipoContacto(TipoContacto tipoContacto)
        {
            base.AddObject("TipoContacto", tipoContacto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Noticias EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNoticias(Noticias noticias)
        {
            base.AddObject("Noticias", noticias);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Carreras")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Carreras : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Carreras object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Carreras CreateCarreras(global::System.Int64 id)
        {
            Carreras carreras = new Carreras();
            carreras.Id = id;
            return carreras;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TipoCarrera
        {
            get
            {
                return _TipoCarrera;
            }
            set
            {
                OnTipoCarreraChanging(value);
                ReportPropertyChanging("TipoCarrera");
                _TipoCarrera = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TipoCarrera");
                OnTipoCarreraChanged();
            }
        }
        private Nullable<global::System.Int32> _TipoCarrera;
        partial void OnTipoCarreraChanging(Nullable<global::System.Int32> value);
        partial void OnTipoCarreraChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK_Carreras_TipoCarrera", "TipoCarrera")]
        public TipoCarrera TipoCarrera1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoCarrera>("Database1Model.FK_Carreras_TipoCarrera", "TipoCarrera").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoCarrera>("Database1Model.FK_Carreras_TipoCarrera", "TipoCarrera").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TipoCarrera> TipoCarrera1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoCarrera>("Database1Model.FK_Carreras_TipoCarrera", "TipoCarrera");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TipoCarrera>("Database1Model.FK_Carreras_TipoCarrera", "TipoCarrera", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    /// 

    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Contactos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [MetadataType(typeof(Contactos_Validar))]    
    public partial class Contactos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Contactos object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Contactos CreateContactos(global::System.Int64 id)
        {
            Contactos contactos = new Contactos();
            contactos.Id = id;
            
            return contactos;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Correo
        {
            get
            {
                return _Correo;
            }
            set
            {
                OnCorreoChanging(value);
                ReportPropertyChanging("Correo");
                _Correo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Correo");
                OnCorreoChanged();
            }
        }
        private global::System.String _Correo;
        partial void OnCorreoChanging(global::System.String value);
        partial void OnCorreoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Asunto
        {
            get
            {
                return _Asunto;
            }
            set
            {
                OnAsuntoChanging(value);
                ReportPropertyChanging("Asunto");
                _Asunto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Asunto");
                OnAsuntoChanged();
            }
        }
        private global::System.String _Asunto;
        partial void OnAsuntoChanging(global::System.String value);
        partial void OnAsuntoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TipoContacto
        {
            get
            {
                return _TipoContacto;
            }
            set
            {
                OnTipoContactoChanging(value);
                ReportPropertyChanging("TipoContacto");
                _TipoContacto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TipoContacto");
                OnTipoContactoChanged();
            }
        }
        private Nullable<global::System.Int32> _TipoContacto;
        partial void OnTipoContactoChanging(Nullable<global::System.Int32> value);
        partial void OnTipoContactoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK_Contactos_TipoContacto", "TipoContacto")]
        public TipoContacto TipoContacto1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoContacto>("Database1Model.FK_Contactos_TipoContacto", "TipoContacto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoContacto>("Database1Model.FK_Contactos_TipoContacto", "TipoContacto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TipoContacto> TipoContacto1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoContacto>("Database1Model.FK_Contactos_TipoContacto", "TipoContacto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TipoContacto>("Database1Model.FK_Contactos_TipoContacto", "TipoContacto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Noticias")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Noticias : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Noticias object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Noticias CreateNoticias(global::System.Int64 id)
        {
            Noticias noticias = new Noticias();
            noticias.Id = id;
            return noticias;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="TipoCarrera")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipoCarrera : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TipoCarrera object.
        /// </summary>
        /// <param name="idCarrera">Initial value of the IdCarrera property.</param>
        public static TipoCarrera CreateTipoCarrera(global::System.Int32 idCarrera)
        {
            TipoCarrera tipoCarrera = new TipoCarrera();
            tipoCarrera.IdCarrera = idCarrera;
            return tipoCarrera;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCarrera
        {
            get
            {
                return _IdCarrera;
            }
            set
            {
                if (_IdCarrera != value)
                {
                    OnIdCarreraChanging(value);
                    ReportPropertyChanging("IdCarrera");
                    _IdCarrera = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCarrera");
                    OnIdCarreraChanged();
                }
            }
        }
        private global::System.Int32 _IdCarrera;
        partial void OnIdCarreraChanging(global::System.Int32 value);
        partial void OnIdCarreraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK_Carreras_TipoCarrera", "Carreras")]
        public EntityCollection<Carreras> Carreras
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Carreras>("Database1Model.FK_Carreras_TipoCarrera", "Carreras");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Carreras>("Database1Model.FK_Carreras_TipoCarrera", "Carreras", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="TipoContacto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipoContacto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TipoContacto object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static TipoContacto CreateTipoContacto(global::System.Int32 id)
        {
            TipoContacto tipoContacto = new TipoContacto();
            tipoContacto.Id = id;
            return tipoContacto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK_Contactos_TipoContacto", "Contactos")]
        public EntityCollection<Contactos> Contactos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Contactos>("Database1Model.FK_Contactos_TipoContacto", "Contactos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Contactos>("Database1Model.FK_Contactos_TipoContacto", "Contactos", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
